
export const ADD_TO_CART = `ADD_TO_CART`
export const REMOVE_FROM_CART = `REMOVE_FROM_CART`
export const CHANGE_QUANITY = `CHANGE_QUANITY`
export const SET_PRODUCTS = `SET_PRODUCTS`
export const GET_PRODUCT = `GET_PRODUCT`
